name: Build

on:
  push:
    branches: [main]

jobs:
  check:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Use node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: Restore node_modules
        uses: actions/cache/restore@v4
        id: restore-node-modules
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Cache node_modules
        uses: actions/cache/save@v4
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Lint check
        run: pnpm lint

      - name: Format check
        run: pnpm format:check

      - name: Build
        run: pnpm build
